# Konekcija na SQL Server (starija sintaksa)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SupplementShop;encrypt=false;
spring.datasource.username=springuser
spring.datasource.password=Spring123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate podesavanja
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Port
server.port=8080